"""
EVA Assistant audit constants.
Copyright (c) 2026 Steve Dogs Studio.
"""

CASE_EVENT_KEYS = {
    "member_banned",
    "member_unbanned",
    "member_kicked",
    "member_timeout_applied",
    "member_timeout_removed",
    "member_moved",
    "member_disconnected",
    "member_voice_moderation_changed",
    "automod_action_timeout",
    "automod_action_quarantined",
}

REASON_EVENT_KEYS = {
    "member_banned",
    "member_unbanned",
    "member_kicked",
    "member_timeout_applied",
    "member_timeout_removed",
    "member_role_added",
    "member_role_removed",
    "members_pruned",
    "member_moved",
    "member_disconnected",
    "member_voice_moderation_changed",
    "bot_added",
    "automod_rule_created",
    "automod_rule_updated",
    "automod_rule_deleted",
    "automod_action_blocked",
    "automod_action_flagged",
    "automod_action_timeout",
    "automod_action_quarantined",
}

IGNORED_CHANGE_ATTRS = {
    "flags",
    "overwrites",
    "permission_overwrites",
    "permissions",
    "applied_tags",
    "available_tags",
    "default_reaction_emoji",
    "emoji",
}

CHANGE_LABELS = {
    "name": "Название",
    "type": "Тип",
    "topic": "Тема",
    "category": "Категория",
    "slowmode_delay": "Медленный режим",
    "rate_limit_per_user": "Медленный режим",
    "nsfw": "NSFW",
    "position": "Позиция",
    "colour": "Цвет",
    "color": "Цвет",
    "hoist": "Показывать отдельно",
    "mentionable": "Можно упоминать",
    "nick": "Никнейм",
    "archived": "Архивирована",
    "locked": "Закрыта",
    "auto_archive_duration": "Автоархив",
    "default_auto_archive_duration": "Автоархив",
    "bitrate": "Битрейт",
    "user_limit": "Лимит участников",
    "code": "Код",
    "temporary": "Временное приглашение",
    "max_age": "Срок действия",
    "max_uses": "Лимит использований",
    "uses": "Использований",
    "description": "Описание",
    "preferred_locale": "Локаль",
    "afk_timeout": "AFK таймер",
    "communication_disabled_until": "Тайм-аут до",
    "mute": "Микрофон выключен",
    "deaf": "Звук выключен",
    "volume": "Громкость",
    "emoji_name": "Эмодзи",
    "available": "Доступен",
    "status": "Статус",
    "entity_type": "Тип события",
    "scheduled_start_time": "Начало",
    "scheduled_end_time": "Окончание",
    "privacy_level": "Приватность",
    "trigger_type": "Триггер",
    "event_type": "Тип проверки",
    "actions": "Действия",
    "exempt_channels": "Исключённые каналы",
    "exempt_roles": "Исключённые роли",
    "default_thread_slowmode_delay": "Медленный режим в ветках",
    "rtc_region": "Регион",
    "video_quality_mode": "Качество видео",
    "default_sort_order": "Порядок сортировки",
    "default_forum_layout": "Вид форума",
    "channel": "Канал",
}
